name=PenguinLib
version=1.0.0
author=Penguin Lab
maintainer=Penguin Lab
sentence=Library for controlling legged robots.
paragraph=Library for controlling legged robots using ESP32, PCA9685 and BNO08x IMU.
category=Device Control
url=https://github.com/Penguin-Lab/PenguinLib/
architectures=esp32
depends=DabbleESP32 (>=1.5.1), Adafruit PWM Servo Driver Library (>=3.0.3), SparkFun BNO08x Cortex Based IMU (>=1.0.6)